#!/usr/bin/env python3
"""
chunks_to_langchain_oracle_vs.py

Load temp/output_chunks.json into an Oracle-backed LangChain vector store
using the same Ollama embedding model pattern used by graph_store.py.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import oracledb

from graphrag_builder import _ollama_embed, _ollama_list_models, _prompt_ollama_model_required


def _read_chunks(path: Path) -> list[dict]:
    if not path.exists():
        raise RuntimeError(f"Chunks file not found: {path}")
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise RuntimeError(f"Invalid JSON in {path}: {exc}") from exc
    chunks = payload.get("chunks", [])
    if not isinstance(chunks, list) or not chunks:
        raise RuntimeError(f"{path} must contain a non-empty 'chunks' array.")
    return chunks


def _normalize_chunks(chunks: list[dict]) -> tuple[list[str], list[dict]]:
    normalized: list[tuple[str, str, dict]] = []
    for idx, chunk in enumerate(chunks):
        if not isinstance(chunk, dict):
            continue
        text = str(chunk.get("text", "")).strip()
        if not text:
            continue
        metadata = chunk.get("metadata")
        if not isinstance(metadata, dict):
            metadata = {}
        uuid = str(metadata.get("uuid", "")).strip() or f"chunk-{idx + 1}"
        ref = str(metadata.get("ref", "")).strip()
        meta = {"uuid": uuid, "ref": ref}
        normalized.append((uuid, text, meta))

    if not normalized:
        raise RuntimeError("No non-empty chunks were found in input.")

    normalized.sort(key=lambda item: item[0])
    texts = [item[1] for item in normalized]
    metadatas = [item[2] for item in normalized]
    return texts, metadatas


def _load_oracle_vs_class():
    try:
        from langchain_community.vectorstores import OracleVS  # type: ignore
        return OracleVS
    except Exception:
        try:
            from langchain_community.vectorstores.oraclevs import OracleVS  # type: ignore
            return OracleVS
        except Exception as exc:
            raise RuntimeError(
                "LangChain Oracle vector store not available. Install dependencies with:\n"
                "  .venv/bin/python -m pip install langchain-community"
            ) from exc


def _load_distance_strategy():
    try:
        from langchain_community.vectorstores.oraclevs import DistanceStrategy  # type: ignore
        return DistanceStrategy
    except Exception:
        return None


def _load_embeddings_base():
    try:
        from langchain_core.embeddings import Embeddings  # type: ignore
        return Embeddings
    except Exception:
        class Embeddings:  # type: ignore
            pass
        return Embeddings


def _build_embeddings_adapter(embed_model: str, ollama_url: str):
    Embeddings = _load_embeddings_base()

    class OllamaEmbeddingsAdapter(Embeddings):
        def embed_documents(self, texts: list[str]) -> list[list[float]]:
            return [_ollama_embed(text, embed_model, ollama_url) for text in texts]

        def embed_query(self, text: str) -> list[float]:
            return _ollama_embed(text, embed_model, ollama_url)

    return OllamaEmbeddingsAdapter()


def _store_chunks(oracle_vs_class, conn, texts: list[str], metadatas: list[dict], embeddings, table_name: str):
    distance_strategy = _load_distance_strategy()
    kwargs = {"client": conn, "table_name": table_name}
    if distance_strategy is not None:
        kwargs["distance_strategy"] = distance_strategy.EUCLIDEAN_DISTANCE

    return oracle_vs_class.from_texts(
        texts=texts,
        embedding=embeddings,
        metadatas=metadatas,
        **kwargs,
    )


def _table_exists(conn: oracledb.Connection, table_name: str) -> bool:
    with conn.cursor() as cur:
        cur.execute(
            "SELECT COUNT(*) FROM user_tables WHERE table_name = UPPER(:name)",
            name=table_name,
        )
        row = cur.fetchone()
    return bool(row and row[0] and int(row[0]) > 0)


def _append_chunks_existing_table(
    oracle_vs_class,
    conn,
    texts: list[str],
    metadatas: list[dict],
    embeddings,
    table_name: str,
):
    distance_strategy = _load_distance_strategy()
    kwargs = {"client": conn, "embedding_function": embeddings, "table_name": table_name}
    if distance_strategy is not None:
        kwargs["distance_strategy"] = distance_strategy.EUCLIDEAN_DISTANCE

    store = oracle_vs_class(**kwargs)
    store.add_texts(texts=texts, metadatas=metadatas)
    return store


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Store output_chunks.json in Oracle LangChain Vector Store."
    )
    parser.add_argument(
        "--chunks-input",
        type=Path,
        default=Path("temp/output_chunks.json"),
        help="Path to chunk JSON generated by graph_extract.py",
    )
    parser.add_argument("--db-user", required=True, help="Oracle username")
    parser.add_argument("--db-password", required=True, help="Oracle password")
    parser.add_argument("--db-dsn", required=True, help="Oracle DSN, e.g. host:1521/FREEPDB1")
    parser.add_argument(
        "--table-name",
        default="LANGCHAIN_CHUNKS_VS",
        help="Oracle vector store table name",
    )
    parser.add_argument(
        "--embed-model",
        default=None,
        help="Ollama embedding model (optional; otherwise selected interactively)",
    )
    parser.add_argument("--ollama-url", default="http://localhost:11434", help="Ollama base URL")
    args = parser.parse_args()

    chunks = _read_chunks(args.chunks_input)
    texts, metadatas = _normalize_chunks(chunks)

    try:
        available_models = _ollama_list_models(args.ollama_url)
    except Exception as exc:
        raise RuntimeError(
            f"Could not fetch Ollama model list from {args.ollama_url}: {exc}"
        ) from exc
    if not available_models:
        raise RuntimeError("No Ollama models discovered. Run scripts/list_ollama_models.py.")

    print("\nOllama models available:")
    for idx, model_name in enumerate(available_models, start=1):
        print(f"  {idx}. {model_name}")
    embed_model = _prompt_ollama_model_required("Embedding", available_models, args.embed_model)

    OracleVS = _load_oracle_vs_class()
    embeddings = _build_embeddings_adapter(embed_model, args.ollama_url)

    print("\nConnecting to Oracle …")
    conn = oracledb.connect(user=args.db_user, password=args.db_password, dsn=args.db_dsn)
    try:
        if _table_exists(conn, args.table_name):
            print(
                f"Table {args.table_name} already exists. "
                f"Appending {len(texts)} chunks using {embed_model} via Ollama …"
            )
            _append_chunks_existing_table(
                oracle_vs_class=OracleVS,
                conn=conn,
                texts=texts,
                metadatas=metadatas,
                embeddings=embeddings,
                table_name=args.table_name,
            )
        else:
            print(
                f"Table {args.table_name} does not exist. "
                f"Creating and storing {len(texts)} chunks using {embed_model} via Ollama …"
            )
            _store_chunks(
                oracle_vs_class=OracleVS,
                conn=conn,
                texts=texts,
                metadatas=metadatas,
                embeddings=embeddings,
                table_name=args.table_name,
            )
    finally:
        conn.close()

    print("\n" + "=" * 60)
    print("LANGCHAIN VECTOR STORE POPULATED")
    print("=" * 60)
    print(f"Chunks input : {args.chunks_input.resolve()}")
    print(f"Table name   : {args.table_name}")
    print(f"Rows loaded  : {len(texts)}")
    print(f"Embeddings   : {embed_model} via Ollama")
    print("=" * 60)
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:
        print(f"[error] {exc}", file=sys.stderr)
        raise SystemExit(1)
