#!/usr/bin/env python3
"""
graph_store.py — GraphRAG store phase

This script runs the SQL generation/storage phase only:
  - Reads schema JSON (extract_graph_schema-like output) from file
  - Reads temp/output_chunks.json for source document references
  - Generates embeddings and a SQL setup script
  - Persists UUID provenance for each vertex/edge row in a `uuids` column
"""

from __future__ import annotations

import argparse
import getpass
import json
import os
import sys
from pathlib import Path

import oracledb

from graphrag_builder import (
    enrich_schema_with_chunk_uuids,
    _graph_exists,
    get_existing_edge_directions,
    _openai_embed,
    _ollama_embed,
    _ollama_list_models,
    _prompt_openai_model_required,
    _prompt_ollama_model_required,
    generate_sql_script,
)


def _read_json(path: Path) -> dict:
    if not path.exists():
        raise RuntimeError(f"Required file not found: {path}")
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise RuntimeError(f"Invalid JSON in {path}: {exc}") from exc


def main() -> None:
    parser = argparse.ArgumentParser(
        description="GraphRAG store phase: generate SQL from extracted schema JSON"
    )
    parser.add_argument(
        "--schema-input",
        type=Path,
        default=Path("temp/output_schema.json"),
        help="Path to schema JSON generated by graph_extract.py",
    )
    parser.add_argument(
        "--chunks-input",
        type=Path,
        default=Path("temp/output_chunks.json"),
        help="Path to temp/output_chunks.json generated by graph_extract.py",
    )
    parser.add_argument("--graph-name", required=True, help="Oracle Property Graph name")
    parser.add_argument(
        "--sql-output",
        default=Path("temp/graphrag_setup.sql"),
        type=Path,
        help="Destination SQL file",
    )
    parser.add_argument(
        "--embed-provider",
        choices=["ollama", "openai"],
        default="ollama",
        help="Embedding provider used while generating SQL vectors",
    )
    parser.add_argument(
        "--embed-model",
        default=None,
        help="Ollama embedding model (required when --embed-provider ollama unless provided interactively)",
    )
    parser.add_argument(
        "--openai-embed-model",
        default=None,
        help="OpenAI embedding model (required when --embed-provider openai unless provided interactively)",
    )
    parser.add_argument("--embed-dim", type=int, default=768, help="Embedding dimension")
    parser.add_argument("--ollama-url", default="http://localhost:11434", help="Ollama base URL")
    parser.add_argument(
        "--openai-base-url",
        default="https://api.openai.com/v1",
        help="OpenAI API base URL (used when --embed-provider openai)",
    )
    parser.add_argument("--force-recreate", action="store_true", help="Include SQL to drop/recreate schema")
    parser.add_argument(
        "--create-user",
        action="store_true",
        help="Include user creation SQL block at top of generated file",
    )
    parser.add_argument(
        "--append-existing",
        action="store_true",
        help="Generate insert-only SQL for an already existing graph (no DDL, no recreate)",
    )
    parser.add_argument("--db-user", default=None, help="Oracle username for graph existence checks")
    parser.add_argument("--db-password", default=None, help="Oracle password for graph existence checks")
    parser.add_argument("--db-dsn", default=None, help="Oracle DSN for graph existence checks")
    args = parser.parse_args()
    if args.append_existing and args.force_recreate:
        raise RuntimeError("--append-existing cannot be combined with --force-recreate.")

    db_check_values = [args.db_user, args.db_password, args.db_dsn]
    provided_db_fields = sum(1 for value in db_check_values if value)
    if provided_db_fields not in (0, 3):
        raise RuntimeError(
            "For Oracle graph checks, provide all of --db-user, --db-password, and --db-dsn."
        )

    edge_direction_overrides: dict[str, tuple[str, str]] = {}
    if provided_db_fields == 3:
        conn = oracledb.connect(user=args.db_user, password=args.db_password, dsn=args.db_dsn)
        try:
            exists = _graph_exists(conn, args.graph_name)
            if exists:
                edge_direction_overrides = get_existing_edge_directions(conn, args.graph_name)
        finally:
            conn.close()

        if exists and not args.append_existing:
            print(
                f"[info] Graph {args.graph_name} already exists in USER_PROPERTY_GRAPHS; "
                "forcing append-existing mode."
            )
            args.append_existing = True
        elif not exists and args.append_existing:
            raise RuntimeError(
                f"Graph {args.graph_name} does not exist in USER_PROPERTY_GRAPHS; "
                "--append-existing cannot be used."
            )

    schema = _read_json(args.schema_input)
    chunks_payload = _read_json(args.chunks_input)
    schema = enrich_schema_with_chunk_uuids(schema, chunks_payload)
    args.schema_input.parent.mkdir(parents=True, exist_ok=True)
    args.schema_input.write_text(
        json.dumps(schema, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    print(f"[info] Normalized schema UUID provenance: {args.schema_input.resolve()}")

    if "vertex" not in schema or "edge" not in schema:
        raise RuntimeError(
            f"{args.schema_input} must contain at least 'vertex' and 'edge' arrays."
        )

    reference_docs = chunks_payload.get("reference_docs", [])
    if not isinstance(reference_docs, list) or not reference_docs:
        raise RuntimeError(
            f"{args.chunks_input} must contain a non-empty 'reference_docs' list."
        )

    embed_info = ""
    if args.embed_provider == "ollama":
        try:
            available_models = _ollama_list_models(args.ollama_url)
        except Exception as exc:
            raise RuntimeError(
                f"Could not fetch Ollama model list from {args.ollama_url}: {exc}"
            ) from exc
        if not available_models:
            raise RuntimeError("No Ollama models discovered. Run scripts/list_ollama_models.py.")

        print("\nOllama models available:")
        for idx, model_name in enumerate(available_models, start=1):
            print(f"  {idx}. {model_name}")
        embed_model = _prompt_ollama_model_required(
            "Embedding", available_models, args.embed_model
        )
        embed_fn = lambda text: _ollama_embed(text, embed_model, args.ollama_url)
        embed_info = f"{embed_model} ({args.embed_dim}d) via Ollama"
    else:
        openai_api_key = os.getenv("OPENAI_API_KEY")
        if not openai_api_key:
            raise RuntimeError(
                "OPENAI_API_KEY is required when --embed-provider openai is used."
            )
        openai_embed_model = _prompt_openai_model_required(
            "OpenAI embedding", args.openai_embed_model
        )
        embed_fn = lambda text: _openai_embed(
            text, openai_embed_model, openai_api_key, args.openai_base_url
        )
        embed_info = f"{openai_embed_model} ({args.embed_dim}d) via OpenAI"

    create_user_info: tuple[str, str] | None = None
    if args.create_user:
        print("\n[3/4] Collecting user creation info (no DB connection needed) …")
        username = input("  New username [graphuser]: ").strip() or "graphuser"
        password = getpass.getpass(f"  Password for {username} [Welcome12345]: ").strip() or "Welcome12345"
        create_user_info = (username, password)
        print(f"  User creation SQL will be included in {args.sql_output}.")
    else:
        print("\n[3/4] Skipping user creation (no --create-user flag).")

    source_docs_str = ", ".join(reference_docs)

    print(f"\n[4/4] Generating embeddings and building SQL script → {args.sql_output} …")
    sql_content = generate_sql_script(
        schema=schema,
        graph_name=args.graph_name,
        source_docs_str=source_docs_str,
        embed_fn=embed_fn,
        emb_dim=args.embed_dim,
        create_user_info=create_user_info,
        force_recreate=args.force_recreate,
        append_only=args.append_existing,
        edge_direction_overrides=edge_direction_overrides if args.append_existing else None,
    )
    args.sql_output.parent.mkdir(parents=True, exist_ok=True)
    args.sql_output.write_text(sql_content, encoding="utf-8")

    print("\n" + "=" * 60)
    print("SQL SCRIPT GENERATED")
    print("=" * 60)
    print(f"File          : {args.sql_output.resolve()}")
    print(f"Graph         : {args.graph_name}")
    print(f"Schema input  : {args.schema_input.resolve()}")
    print(f"Chunks input  : {args.chunks_input.resolve()}")
    print(f"Sources       : {source_docs_str}")
    print(f"Embeddings    : {embed_info}")
    print(f"Mode          : {'append-existing (insert only)' if args.append_existing else 'create/update (DDL + inserts)'}")
    print("UUID field    : included (`uuids` JSON text on vertex/edge rows)")
    if create_user_info:
        print("User creation : included — run that block as DBA/SYSDBA first")
    print("=" * 60)


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:
        print(f"[error] {exc}", file=sys.stderr)
        sys.exit(1)
